FROM ipburger/mysql-alpine.docker:release
LABEL maintainer="jgaviri8@gmail.com"

ENV MYSQL_DATABASE products_db
ENV MYSQL_USER products_admin
ENV MYSQL_PASSWORD products_admin
ENV MYSQL_ROOT_PASSWORD 111111

CMD ["/startup.sh"]
